version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for npm (for JavaScript/Node.js projects)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    
  # Uncomment and adjust for other ecosystems as needed
  - package-ecosystem: "pip" # for Python
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10